# Статические тексты интерфейса
STATIC_TEXTS = {
    "ru": {
        "loading": "Загрузка...",
        "title_copy_link": "Скопировать ключ",
        "title_share": "Поделиться",
        "title_qr": "QR-код",
        "subscription_expires": "Подписка истекает",
        "select_platform": "Выберите платформу",
        "select_app": "Выберите приложение",
        "download_app": "Скачать приложение",
        "add_subscription": "Добавить подписку",
        "manual_setup": "Ручная настройка",
        "copy_link": "Скопировать ссылку",
        "link_copied": "Ссылка скопирована!",
        "error_loading": "Ошибка загрузки данных",
        "retry": "Повторить",
        "ios": "iPhone/iPad",
        "android": "Android",
        "windows": "Windows",
        "macos": "macOS",
        "linux": "Linux",
        "appletv": "Apple TV",
        "androidtv": "Android TV",
        "step": "Шаг",
        "next": "Далее",
        "back": "Назад",
        "finish": "Готово",
        "skip": "Пропустить",
        "country_selector": "Выбор страны",
        "select_country": "Выберите страну сервера",
        "send_to_tv": "Отправить на ТВ",
        "tv_code": "Код с ТВ",
        "send": "Отправить",
        "tv_sent": "Отправлено на ТВ!",
        "tv_error": "Ошибка отправки"
    },
    "en": {
        "loading": "Loading...",
        "title_copy_link": "Copy subscription link",
        "title_share": "Share",
        "title_qr": "QR Code",
        "subscription_expires": "Subscription expires",
        "select_platform": "Select platform",
        "select_app": "Select app",
        "download_app": "Download app",
        "add_subscription": "Add subscription",
        "manual_setup": "Manual setup",
        "copy_link": "Copy link",
        "link_copied": "Link copied!",
        "error_loading": "Error loading data",
        "retry": "Retry",
        "ios": "iPhone/iPad",
        "android": "Android",
        "windows": "Windows",
        "macos": "macOS",
        "linux": "Linux",
        "appletv": "Apple TV",
        "androidtv": "Android TV",
        "step": "Step",
        "next": "Next",
        "back": "Back",
        "finish": "Done",
        "skip": "Skip",
        "country_selector": "Country selection",
        "select_country": "Select server country",
        "send_to_tv": "Send to TV",
        "tv_code": "TV code",
        "send": "Send",
        "tv_sent": "Sent to TV!",
        "tv_error": "Send error"
    }
}

# Динамические тексты (инструкции для приложений)
DINAMIC_TEXTS = {
    "ru": {
        "install_happ_ios": "Скачайте Happ с App Store",
        "install_happ_android": "Скачайте Happ с Google Play или APK",
        "install_happ_windows": "Скачайте и установите Happ для Windows",
        "install_happ_macos": "Скачайте Happ из App Store или DMG",
        "install_happ_linux": "Скачайте AppImage файл Happ",
        "add_subscription_happ": "Нажмите кнопку ниже для автоматического добавления подписки",
        "connect_happ": "В приложении Happ выберите добавленную конфигурацию и нажмите Подключить",
        
        "install_v2raytun_ios": "Скачайте V2rayTun с App Store",
        "install_v2raytun_android": "Скачайте V2rayTun с Google Play или APK",
        "install_v2raytun_windows": "Скачайте и установите V2rayTun для Windows",
        "install_v2raytun_macos": "Скачайте V2rayTun из App Store",
        "add_subscription_v2raytun": "Нажмите кнопку для автоматического добавления",
        "connect_v2raytun": "Выберите конфигурацию и подключитесь",
        
        "install_hiddify": "Скачайте Hiddify для вашей платформы",
        "add_subscription_hiddify": "Нажмите кнопку для импорта подписки",
        "connect_hiddify": "Выберите профиль и нажмите Подключить",
        
        "manual_copy_link": "Скопируйте ссылку подписки",
        "manual_open_app": "Откройте VPN приложение",
        "manual_add_config": "Добавьте конфигурацию вручную, вставив скопированную ссылку",
        "manual_connect": "Подключитесь к VPN"
    },
    "en": {
        "install_happ_ios": "Download Happ from App Store",
        "install_happ_android": "Download Happ from Google Play or APK",
        "install_happ_windows": "Download and install Happ for Windows",
        "install_happ_macos": "Download Happ from App Store or DMG",
        "install_happ_linux": "Download Happ AppImage file",
        "add_subscription_happ": "Click the button below to automatically add subscription",
        "connect_happ": "In Happ app, select the added configuration and click Connect",
        
        "install_v2raytun_ios": "Download V2rayTun from App Store",
        "install_v2raytun_android": "Download V2rayTun from Google Play or APK",
        "install_v2raytun_windows": "Download and install V2rayTun for Windows",
        "install_v2raytun_macos": "Download V2rayTun from App Store",
        "add_subscription_v2raytun": "Click button to automatically add",
        "connect_v2raytun": "Select configuration and connect",
        
        "install_hiddify": "Download Hiddify for your platform",
        "add_subscription_hiddify": "Click button to import subscription",
        "connect_hiddify": "Select profile and click Connect",
        
        "manual_copy_link": "Copy subscription link",
        "manual_open_app": "Open VPN app",
        "manual_add_config": "Add configuration manually by pasting the copied link",
        "manual_connect": "Connect to VPN"
    }
}
